library(here)
library(R.utils)
source(here("tests/testing_functions.R"), local = TRUE)
# create the various test datasets (will be saved in a temp directory)
source(here("tests/create_test_datasets.R"), local = TRUE)
shinytest2::load_app_env()
