version: 0.2

phases:
  build:
    commands:
      - chmod +x ./aws/scripts/push-image.sh
      - ./aws/scripts/push-image.sh $IMAGE_TYPE
  post_build:
    commands:
      - echo Build completed on `date`