# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# system libraries:
#   libcurl -- needed to complete setup-renv
#   libharfbuzz-dev libfribidi-dev -- needed for the textshaping package
#   Also using shinytest2 action to try running test -
# https://cran.r-project.org/web/packages/shinytest2/vignettes/use-ci.html
on:
  pull_request:
    branches: [dev, main]
  
name: Test

jobs:
  test:
    runs-on: ubuntu-22.04

    name: shiny-test-automation

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      IGNORE_COLUMNS: ${{ secrets.IGNORE_COLUMNS }}
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'

      - name: install needed system libs
        shell: bash
        run: |
          sudo apt install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
              
      - uses: r-lib/actions/setup-renv@v2
      
      - name: remove max fails
        run: |
          testthat::set_max_fails(Inf)
        shell: Rscript {0}

      - name: Update chromote so back-to-back tests work
        run: |
          install.packages('chromote', repos = c('https://rstudio.r-universe.dev', 'https://cloud.r-project.org'))
          library(rvest)
          chromote::local_chrome_version(binary = "chrome-headless-shell", quiet = FALSE)
        shell: Rscript {0}
      
      - uses: rstudio/shinytest2/actions/test-app@v1
        with:
          app-dir: "."
          upload-snapshots: true
          
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-4.2-tests
          path: tests
